apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-runner-binding
  namespace: jenkins
subjects:
  - kind: ServiceAccount
    name: default 
    namespace: jenkins
roleRef:
  kind: Role
  name: job-runner
  apiGroup: rbac.authorization.k8s.io
