apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-tests
  namespace: jenkins
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: python
          image: python:3.9
          command: ["pytest", "tests/e2e_test.py"]
          volumeMounts:
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
