apiVersion: v1
kind: Pod
metadata:
  name: e2e-tests
spec:
  containers:
    - name: python
      image: python:3.9
      command:
        - cat
      tty: true
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
