apiVersion: batch/v1
kind: Job
metadata:
  name: pytest-job
  namespace: jenkins
spec:
  template:
    spec:
      containers:
      - name: pytest
        image: python:3.9
        command: ["sh", "-c", "pip install -r requirements.txt && pytest tests/e2e_test.py"]
      restartPolicy: Never
  backoffLimit: 3
